version: '3'

services:
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - postgres

  elasticsearch:
    image: elasticsearch:7.8.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  postgres:
    image: postgres:15.3
    env_file:
      - .env
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12.2
    ports:
      - 5672:5672
    hostname: rabbit1
    env_file:
      - .env

  celery:
    build: .
    restart: always
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - web

  flower:
    image: mher/flower:0.9.5
    command: celery flower --persisten=True
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - fldata:/etc/db/
    depends_on:
      - rabbitmq
    
volumes:
  pgdata: {}
  esdata: {}
  fldata: {}